public class Species
{
    public Int32 Id { get; set; }
    public String ScientificName { get; set; }
    public String Rank { get; set; }
    public String Genus { get; set; }
    public String Family { get; set; }
    public String Author { get; set; }
    public Int32? Year { get; set; }
    public String Bibliography { get; set; }
    public String CommonName { get; set; }
    public String FamilyCommonName { get; set; }
    public String ImageUrl { get; set; }
    public Boolean? SlowerConspicuous { get; set; }
    public String FlowerColor { get; set; }
    public Boolean? FlowerConspicuous { get; set; }
    public String FoliageColor { get; set; }
    public String FoliageTexture { get; set; }
    public String FruitColor { get; set; }
    public Boolean? FruitConspicuous { get; set; }
    public String FruitMonths { get; set; }
    public String BloomMonths { get; set; }
    public Int32? GroundHumidity { get; set; }
    public String GrowthForm { get; set; }
    public String GrowthHabit { get; set; }
    public String GrowthMonths { get; set; }
    public String GrowthRate { get; set; }
    public String EdiblePart { get; set; }
    public Boolean? Vegetable { get; set; }
    public Boolean? Edible { get; set; }
    public Int32? Light { get; set; }
    public Int32? SoilNutriments { get; set; }
    public Int32? SoilSalinity { get; set; }
    public String AnaerobicTolerance { get; set; }
    public Int32? AnaerobicHumidity { get; set; }
    public Int32? AverageHeightCm { get; set; }
    public Int32? MaximumHeightCm { get; set; }
    public Int32? MinimumRootDepthCm { get; set; }
    public Double? PhMaximum { get; set; }
    public Double? PhMinimum { get; set; }
    public Int32? PlantingDaysToHarvest { get; set; }
    public String PlantingDescription { get; set; }
    public String PlantingSowingDescription { get; set; }
    public Int32? PlantingRowSpacingCm { get; set; }
    public Int32? PlantingSpreadCm { get; set; }
    public String Synonyms { get; set; }
    public String Distributions { get; set; }
    public String CommonNames { get; set; }
    public String UrlUsda { get; set; }
    public String UrlTropicos { get; set; }
    public String UrlPowo { get; set; }
    public String UrlTelaBotanica { get; set; }
    public String UrlPlantnet { get; set; }
    public String UrlGbif { get; set; }
    public String UrlOpenfarm { get; set; }
    public String UrlCatminat { get; set; }
    public String UrlWikipediaEn { get; set; }
}