public class Species
{
    public int Id { get; set; }
    public string? ScientificName { get; set; }
    public string? Rank { get; set; }
    public string? Genus { get; set; }
    public string? Family { get; set; }
    public string? Author { get; set; }
    public string? Year { get; set; }
    public string? Bibliography { get; set; }
    public string? CommonName { get; set; }
    public string? FamilyCommonName { get; set; }
    public string? ImageUrl { get; set; }
    public string? SlowerConsipicuous { get; set; }
    public string? FlowerColor { get; set; }
    public string? FlowerConspicuous { get; set; }
    public string? FoliageColor { get; set; }
    public string? FoliageTexture { get; set; }
    public string? FruitColor { get; set; }
    public string? FruitConspicuous { get; set; }
    public string? FruitMonths { get; set; }
    public string? BloomMonths { get; set; }
    public string? GroundHumidity { get; set; }
    public string? GrowthForm { get; set; }
    public string? GrowthHabit { get; set; }
    public string? GrowthMonths { get; set; }
    public string? GrowthRate { get; set; }
    public string? EdiblePart { get; set; }
    public string? Vegetable { get; set; }
    public string? Edible { get; set; }
    public string? Light { get; set; }
    public string? SoilNutriments { get; set; }
    public string? SoilSalinity { get; set; }
    public string? AnaerobicTolerance { get; set; }
    public string? AnaerobicHumidity { get; set; }
    public string? AverageHeightCm { get; set; }
    public string? MaximumHeightCm { get; set; }
    public string? MinimumRootDepthCm { get; set; }
    public string? PhMaximum { get; set; }
    public string? PhMinimum { get; set; }
    public string? PlantingDaysToHarvest { get; set; }
    public string? PlantingDescription { get; set; }
    public string? PlantingSowingDescription { get; set; }
    public string? PlantingRowSpacingCm { get; set; }
    public string? PlantingSpreadCm { get; set; }
    public string? Synonyms { get; set; }
    public string? Distributions { get; set; }
    public string? CommonNames { get; set; }
    public string? UrlUsda { get; set; }
    public string? UrlTropicos { get; set; }
    public string? UrlPowo { get; set; }
    public string? UrlTelaBotanica { get; set; }
    public string? UrlPlantnet { get; set; }
    public string? UrlGbif { get; set; }
    public string? UrlOpenfarm { get; set; }
    public string? UrlCatminat { get; set; }
    public string? UrlWikipediaEn { get; set; }
}